### ISSUE TITLE
Global types are breaking type tets

### ISSUE THREAD

**Issue by Ver0s** [mrazauskas/tsd-lite#358] opened 2023-09-25 12:50 UTC
Hi, first of all I wanted to say thank you for the hard work on the library! 😃

At our project we wanted to introduce type testing using `tsd-lite` along with `tsd-runner-jest`. We did a basic setup according to the docs to make a sort of MVP. The setup is mirrored in this [repro repo](https://github.com/Ver0s/tsd-lite-repro/).

The problem that we encountered is that types from the global scope seem to break the type tests. In this repro we're creating a type test but also importing a function to test its signature. This function is using a global type.

After running `npx jest --config jest.config.tsd.js` you can see that type `ThisIsNull` cannot be found, but it is used in the `id` function. The test would also break if we used `ThisIsNull` directly in the type tests since it would not
be recognized unless it's explicitly imported (which would make it non-global).

## Steps to reproduce:
1. Clone the repo and install dependencies - `git clone` followed by `npm i`
2. Run the tests - `npx jest --config jest.config.tsd.js`
3. Check the result

**Actual result:**
<img src="https://github.com/Ver0s/tsd-lite-repro/assets/89318957/2e72b37d-342b-4503-8efb-41afec6d9ad5" width="350" />

**Expected result:**
`ThisIsNull` type should be known to the runner when importing the `id` function, error shouldn't be thrown

## The question
So we wanted to ask whether we can do something about it right now, maybe we missed something? And if we can - would it require us to get rid of global types or do some hacks to get around problems surrounding them? Or maybe that problem is unsolvable for the time being?

Please let us know, thanks for any help in advance!

CC @erheron

**Comment by mrazauskas** [comment] 2023-09-25 13:21
Thanks for reaching out!

Checked your reproduction. Feels like something is wrong on `tsd-lite` side, because `tsc` compiles the same file with no issues.

Hm.. Interesting what is going on here. I will try to find time to think about it and to dig around.

---

Actually! A better solution could be simply to wait for a brand new type testing tool, which I mentioned here: https://github.com/jest-community/jest-runner-tsd/issues/32.

Just checked it, your reproduction is passing without any issues using this runner. It is near ready to be published. Should be out in 4-6 weeks.

**Comment by mrazauskas** [comment] 2023-09-25 13:33
Quick workaround. Add the following to the test file:

```ts
import '../types.d.ts';
```

`tsd-lite` does not see files which are not imported. It only picks `compilerOptions` from `tsconfig.json` and does not know anything more about files around. That’s a limitation unfortunately. But is fixed in the new runner which will replace `tsd-lite` very soon (;

**Comment by Ver0s** [comment] 2023-09-25 13:53
Thanks for such a quick response and explanation!

It's good to know that we had a good intuition and it's actually an existing limitation. We'll wait for the new runner - amazing work by the way! I'll leave it up to you to decide whether to close or keep this issue open but I personally think it's good to keep it open :)

**Comment by mrazauskas** [comment] 2023-11-13 14:40
[TSTyche](https://tstyche.org), the testing tool I promised, is released. For details, see https://github.com/jest-community/jest-runner-tsd/issues/32#issuecomment-1808258311

Thanks for raising the issue. It gave me another bit of motivation to move on with TSTyche. Give it a try, please. 

It works as expect with case you have described here. So I can close now (;

**Closed by mrazauskas** 2023-11-13 14:40 UTC
